"""Add Mood Model

Revision ID: 45d2b162ca25
Revises: faad7137f203
Create Date: 2025-11-12 23:45:01.910775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d2b162ca25'
down_revision = 'faad7137f203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood_type', sa.String(length=50), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('energy_score', sa.Integer(), nullable=False),
    sa.Column('stress_score', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood')
    # ### end Alembic commands ###
